version: "2"

services:
  web:
    build: .
    command: mix phx.server
    environment:
      MIX_ENV: dev
      PORT: "4000"
    expose:
      - "4000"
    ports:
      - 4000:4000
    volumes:
      - .:/app

  test:
    image: connectfourphoenix_web
    command: mix test
    environment:
      MIX_ENV: test
      PORT: 4001
    volumes_from:
      - web
    ports:
      - 4001:4001
